// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyhMJzv7LLksWn-x4980bwo3vN61qqZuY',
    appId: '1:113523833631:web:390bbe6a24e08eb5a2ce2a',
    messagingSenderId: '113523833631',
    projectId: 'umoja-e98d3',
    authDomain: 'umoja-e98d3.firebaseapp.com',
    storageBucket: 'umoja-e98d3.appspot.com',
    measurementId: 'G-PHLW2B1XEM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcR9i1YP3MFx2T_v5gHk_qikc1w8Qd2Mk',
    appId: '1:113523833631:android:eeee13bc38d5ab5da2ce2a',
    messagingSenderId: '113523833631',
    projectId: 'umoja-e98d3',
    storageBucket: 'umoja-e98d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0P-r07vOzopYfR-DJ0htvIZ2aje9iGqU',
    appId: '1:113523833631:ios:68e3c91cc8c934aca2ce2a',
    messagingSenderId: '113523833631',
    projectId: 'umoja-e98d3',
    storageBucket: 'umoja-e98d3.appspot.com',
    iosBundleId: 'com.example.umoja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0P-r07vOzopYfR-DJ0htvIZ2aje9iGqU',
    appId: '1:113523833631:ios:68e3c91cc8c934aca2ce2a',
    messagingSenderId: '113523833631',
    projectId: 'umoja-e98d3',
    storageBucket: 'umoja-e98d3.appspot.com',
    iosBundleId: 'com.example.umoja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyhMJzv7LLksWn-x4980bwo3vN61qqZuY',
    appId: '1:113523833631:web:6ed48868eb0a5dd7a2ce2a',
    messagingSenderId: '113523833631',
    projectId: 'umoja-e98d3',
    authDomain: 'umoja-e98d3.firebaseapp.com',
    storageBucket: 'umoja-e98d3.appspot.com',
    measurementId: 'G-G4LFLWGNJY',
  );
}
